=== wmo-im/wmdr2-devt/schemas/wmdr2-record-feature.schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://wmo-im.github.io/wmdr2-devt/schemas/wmdr2-record-feature.schema.json",
  "title": "WMDR2 facility-centric Feature",
  "type": "object",
  "required": [
    "type",
    "id",
    "properties"
  ],
  "additionalProperties": true,
  "properties": {
    "type": {
      "const": "Feature"
    },
    "id": {
      "type": "string",
      "pattern": "^facility:"
    },
    "geometry": {
      "anyOf": [
        {
          "$ref": "wmdr2-common.schema.json#/$defs/pointGeometry"
        },
        {
          "type": "null"
        }
      ]
    },
    "temporalGeometry": {
      "$ref": "wmdr2-common.schema.json#/$defs/temporalGeometry"
    },
    "time": {
      "anyOf": [
        {
          "type": "object",
          "properties": {
            "interval": {
              "type": "array",
              "items": {
                "$ref": "wmdr2-common.schema.json#/$defs/dateOrOpen"
              },
              "minItems": 2,
              "maxItems": 2
            }
          },
          "required": [
            "interval"
          ],
          "additionalProperties": true
        },
        {
          "type": "null"
        }
      ]
    },
    "conformsTo": {
      "type": "array",
      "minItems": 1,
      "maxItems": 1,
      "items": {
        "const": "http://wigos.wmo.int/spec/wmdr/2/conf/core"
      }
    },
    "properties": {
      "type": "object",
      "required": [
        "type",
        "title"
      ],
      "additionalProperties": true,
      "allOf": [
        {
          "not": {
            "required": [
              "environment"
            ]
          }
        },
        {
          "not": {
            "required": [
              "temporalProgramAffiliation"
            ]
          }
        },
        {
          "not": {
            "required": [
              "temporalTerritory"
            ]
          }
        },
        {
          "not": {
            "required": [
              "temporalReportingStatus"
            ]
          }
        },
        {
          "not": {
            "required": [
              "externalIds"
            ]
          }
        },
        {
          "not": {
            "required": [
              "facilitySet"
            ]
          }
        },
        {
          "not": {
            "required": [
              "temporalClimateZone"
            ]
          }
        },
        {
          "not": {
            "required": [
              "temporalSurfaceCover"
            ]
          }
        },
        {
          "not": {
            "required": [
              "temporalPopulation"
            ]
          }
        },
        {
          "not": {
            "required": [
              "temporalSurfaceRoughness"
            ]
          }
        },
        {
          "not": {
            "required": [
              "temporalGeometry"
            ]
          }
        }
      ],
      "properties": {
        "type": {
          "const": "facility"
        },
        "title": {
          "type": "string"
        },
        "description": {
          "type": "string"
        },
        "created": {
          "type": "string"
        },
        "updated": {
          "type": "string"
        },
        "contacts": {
          "type": "array",
          "items": {
            "$ref": "wmdr2-common.schema.json#/$defs/contact"
          }
        },
        "keywords": {
          "type": "array",
          "items": {
            "type": "string"
          }
        },
        "links": {
          "type": "array",
          "items": {
            "$ref": "wmdr2-common.schema.json#/$defs/link"
          }
        },
        "facilitySets": {
          "type": "array",
          "items": {
            "type": "string",
            "pattern": "^facilitySet:"
          }
        },
        "historicalProgramAffiliation": {
          "$ref": "wmdr2-common.schema.json#/$defs/historicalProgramAffiliation"
        },
        "historicalTerritory": {
          "$ref": "wmdr2-common.schema.json#/$defs/historicalTerritory"
        },
        "historicalEnvironment": {
          "$ref": "wmdr2-common.schema.json#/$defs/historicalEnvironment"
        },
        "schedules": {
          "type": "array",
          "items": {
            "$ref": "wmdr2-common.schema.json#/$defs/schedule"
          }
        },
        "observations": {
          "type": "array",
          "items": {
            "$ref": "wmdr2-common.schema.json#/$defs/observation"
          }
        },
        "instruments": {
          "type": "array",
          "items": {
            "$ref": "wmdr2-common.schema.json#/$defs/instrument"
          }
        },
        "reporting": {
          "type": "array",
          "items": {
            "$ref": "wmdr2-common.schema.json#/$defs/reporting"
          }
        },
        "deployments": {
          "type": "array",
          "items": {
            "$ref": "wmdr2-common.schema.json#/$defs/deployment"
          }
        }
      }
    }
  }
}

=== wmo-im/wmdr2-devt/results/wmdr2_json_examples/embedded/20230331_0-250-1005-SARg.json
{
  "type": "Feature",
  "id": "facility:0-250-1005-SARg",
  "geometry": {
    "type": "Point",
    "coordinates": [
      6.07,
      45.07,
      2850
    ]
  },
  "time": {
    "interval": [
      "1949-01-01",
      ".."
    ]
  },
  "conformsTo": [
    "http://wigos.wmo.int/spec/wmdr/2/conf/core"
  ],
  "properties": {
    "type": "facility",
    "title": "Sarennes Glacier",
    "created": "2023-03-31T00:00:00Z",
    "updated": "2023-03-31T00:00:00Z",
    "description": "WMDR2 facility record for Sarennes Glacier",
    "contacts": [
      {
        "organization": "Université Grenoble-Alpes",
        "roles": [
          "owner"
        ]
      },
      {
        "name": "SIX,Delphine,Mme",
        "organization": "Université Grenoble-Alpes",
        "phones": [
          {
            "value": "+33(0)476824239"
          }
        ],
        "emails": [
          {
            "value": "delphine.six@univ-grenoble-alpes.fr"
          }
        ],
        "addresses": [
          {
            "deliveryPoint": [
              "UGA - IGE CS 40700"
            ],
            "city": "Grenoble",
            "postalCode": "38058",
            "country": "FRA"
          }
        ],
        "roles": [
          "principalInvestigator"
        ]
      },
      {
        "organization": "World Meteorological Organization WMO and Federal Office for Meteorology and Climatology MeteoSwiss",
        "emails": [
          {
            "value": "oscar@wmo.int"
          }
        ],
        "links": [
          {
            "href": "https://oscar.wmo.int/surface",
            "rel": "about",
            "type": "text/html"
          }
        ]
      }
    ],
    "keywords": [
      "0-250-1005-SARg",
      "Sarennes Glacier"
    ],
    "links": [
      {
        "href": "https://glacioclim.osug.fr/Glacier-de-Sarennes-203",
        "rel": "about",
        "type": "text/html"
      }
    ],
    "facilityType": "landOnIce",
    "wmoRegion": "europe",
    "temporalTerritory": [
      {
        "territory": "FRA",
        "date": "1949-01-01"
      }
    ],
    "schedules": [
      {
        "@type": "Event",
        "start": "0001-01-01T00:00:00",
        "timeZone": "UTC",
        "duration": "P1D",
        "recurrenceRules": [
          {
            "@type": "RecurrenceRule",
            "frequency": "daily"
          }
        ],
        "wmo.int:aggregation": {
          "temporalAggregate": "PT1H"
        },
        "uid": "schedule_38ade7ec764d"
      }
    ],
    "observations": [
      {
        "id": "observation:12010",
        "title": "domain: terrestrial; geometry: unknown; variable: 12010",
        "time": {
          "interval": [
            "1949-01-01",
            ".."
          ]
        },
        "observedVariable": 12010,
        "observedGeometryType": "unknown",
        "observedDomain": "terrestrial",
        "programAffiliations": [
          "nonAffiliated"
        ],
        "deployments": [
          "deployment:id_14ca4229-9da7-4f5c-8e35-5a30369f353c"
        ],
        "reporting": {
          "internationalExchange": [
            false
          ],
          "temporalAggregate": [
            "PT1H"
          ],
          "dataPolicy": [
            {
              "attribution": {
                "originator": {
                  "role": null
                }
              }
            }
          ]
        }
      }
    ],
    "deployments": [
      {
        "id": "deployment:id_14ca4229-9da7-4f5c-8e35-5a30369f353c",
        "time": {
          "interval": [
            "1949-01-01",
            ".."
          ]
        },
        "observingMethod": "unknown",
        "temporalObservingSchedule": [
          {
            "observingSchedule": "schedule_38ade7ec764d",
            "date": "1949-01-01"
          }
        ]
      }
    ]
  }
}

=== wmo-im/wmdr2-devt/results/wmdr2_json_examples/catalogue_records/20221124_0-578-0-92100.json
{
  "type": "Feature",
  "id": "facility:0-578-0-92100",
  "geometry": {
    "type": "Point",
    "coordinates": [
      2.4668,
      -71.9563,
      1235
    ]
  },
  "time": {
    "interval": [
      "2007-01-01",
      ".."
    ]
  },
  "conformsTo": [
    "http://wigos.wmo.int/spec/wmdr/2/conf/core"
  ],
  "properties": {
    "type": "facility",
    "title": "TROLL AIRFIELD",
    "created": "2022-11-24T00:00:00Z",
    "updated": "2022-11-24T00:00:00Z",
    "description": "WMDR2 facility record for TROLL AIRFIELD",
    "contacts": [
      {
        "identifier": "contact:norwegian-polar-institute--8f27a0e0",
        "organization": "Norwegian Polar Institute",
        "roles": [
          "owner"
        ],
        "links": [
          {
            "rel": "about",
            "href": "../contacts.json#contact:norwegian-polar-institute--8f27a0e0",
            "type": "application/json"
          }
        ]
      },
      {
        "identifier": "contact:christina.pedersen@npolar.no",
        "name": "Pedersen,Christina Alsvik,Dr.",
        "organization": "Norwegian Polar Institute",
        "roles": [
          "principalInvestigator"
        ],
        "links": [
          {
            "rel": "about",
            "href": "../contacts.json#contact:christina.pedersen@npolar.no",
            "type": "application/json"
          }
        ]
      },
      {
        "identifier": "contact:oscar@wmo.int",
        "organization": "World Meteorological Organization WMO and Federal Office for Meteorology and Climatology MeteoSwiss",
        "links": [
          {
            "rel": "about",
            "href": "../contacts.json#contact:oscar@wmo.int",
            "type": "application/json"
          }
        ]
      }
    ],
    "keywords": [
      "0-578-0-92100",
      "TROLL AIRFIELD"
    ],
    "facilityType": "landOnIce",
    "wmoRegion": "antarctica",
    "temporalTerritory": [
      {
        "territory": "NOR",
        "date": "2007-01-01"
      }
    ],
    "temporalProgramAffiliation": [
      {
        "programAffiliation": "GOSGeneral",
        "reportingStatus": "operational",
        "date": "2022-11-22"
      },
      {
        "programAffiliation": "nonAffiliated",
        "reportingStatus": "operational",
        "date": "2022-11-22"
      }
    ],
    "observations": [
      {
        "id": "observation:216",
        "title": "domain: atmosphere; geometry: point; variable: 216",
        "time": {
          "interval": [
            "2007-01-01",
            ".."
          ]
        },
        "observedVariable": 216,
        "observedGeometryType": "point",
        "observedDomain": "atmosphere",
        "programAffiliations": [
          "nonAffiliated",
          "GOSGeneral"
        ],
        "deployments": [
          "deployment:id_98af3b44-3633-4017-b16a-8dfb89707c55"
        ]
      },
      {
        "id": "observation:224",
        "title": "domain: atmosphere; geometry: point; variable: 224",
        "time": {
          "interval": [
            "2007-01-01",
            ".."
          ]
        },
        "observedVariable": 224,
        "observedGeometryType": "point",
        "observedDomain": "atmosphere",
        "programAffiliations": [
          "nonAffiliated",
          "GOSGeneral"
        ],
        "deployments": [
          "deployment:id_1c5901b1-da2a-46dd-9d48-6afb6a876cb4"
        ]
      },
      {
        "id": "observation:12249",
        "title": "domain: atmosphere; geometry: point; variable: 12249",
        "time": {
          "interval": [
            "2022-11-22",
            ".."
          ]
        },
        "observedVariable": 12249,
        "observedGeometryType": "point",
        "observedDomain": "atmosphere",
        "programAffiliations": [
          "nonAffiliated",
          "GOSGeneral"
        ],
        "deployments": [
          "deployment:id_86c6bc2c-7e41-4c5e-b8db-7f6147d34c68"
        ]
      },
      {
        "id": "observation:12005",
        "title": "domain: atmosphere; geometry: point; variable: 12005",
        "time": {
          "interval": [
            "2007-01-01",
            ".."
          ]
        },
        "observedVariable": 12005,
        "observedGeometryType": "point",
        "observedDomain": "atmosphere",
        "programAffiliations": [
          "nonAffiliated",
          "GOSGeneral"
        ],
        "deployments": [
          "deployment:id_1219f00c-7af8-432b-be2a-9a442a76e14a"
        ]
      }
    ],
    "deployments": [
      {
        "id": "deployment:id_98af3b44-3633-4017-b16a-8dfb89707c55",
        "time": {
          "interval": [
            "2007-01-01",
            ".."
          ]
        },
        "observingMethod": 111
      },
      {
        "id": "deployment:id_1c5901b1-da2a-46dd-9d48-6afb6a876cb4",
        "time": {
          "interval": [
            "2007-01-01",
            ".."
          ]
        },
        "observingMethod": 188
      },
      {
        "id": "deployment:id_86c6bc2c-7e41-4c5e-b8db-7f6147d34c68",
        "time": {
          "interval": [
            "2022-11-22",
            ".."
          ]
        },
        "observingMethod": 254
      },
      {
        "id": "deployment:id_1219f00c-7af8-432b-be2a-9a442a76e14a",
        "time": {
          "interval": [
            "2007-01-01",
            ".."
          ]
        },
        "observingMethod": 63
      }
    ]
  }
}

=== wmo-im/wmdr2-devt/results/wmdr2_json_examples_catalogue_version/20260604_0-70-0-Lukavac.json
{
  "type": "Feature",
  "id": "0-70-0-Lukavac",
  "conformsTo": [
    "http://wigos.wmo.int/spec/wmdr/2/conf/core"
  ],
  "geometry": {
    "type": "Point",
    "coordinates": [
      18.5262,
      44.5213,
      188.17
    ]
  },
  "properties": {
    "type": "facility",
    "title": "LUKAVAC",
    "created": "2026-06-04T00:00:00Z",
    "updated": "2026-06-04T00:00:00Z",
    "facilityType": "underwaterFixed",
    "territory": [
      {
        "territory": "BIH",
        "time": {
          "interval": [
            "2019-08-05",
            ".."
          ]
        }
      }
    ],
    "wmoRegion": "europe",
    "observationSeries": [
      {
        "id": "observationSeries:166",
        "title": "domain: terrestrial; variable: 166",
        "observedProperty": 166,
        "observedDomain": {
          "domain": "terrestrial"
        },
        "observingConfigurations": [
          {
            "time": {
              "interval": [
                "2019-08-05",
                ".."
              ]
            },
            "observingMethod": 356
          }
        ]
      }
    ],
    "keywords": [
      "0-70-0-Lukavac",
      "LUKAVAC"
    ],
    "links": [
      {
        "href": "https://www.fhmzbih.gov.ba/latinica/index.php",
        "rel": "about",
        "type": "text/html"
      }
    ],
    "contactAssignments": [
      {
        "contact": "contact:merima.trako@fhmzbih.gov.ba",
        "roles": [
          "pointOfContact"
        ]
      }
    ]
  },
  "time": {
    "interval": [
      "2019-08-05",
      ".."
    ],
    "resolution": "P1D"
  },
  "temporalGeometry": {
    "type": "MovingPoint",
    "coordinates": [
      [
        18.5262,
        44.5213,
        188.17
      ]
    ],
    "dates": [
      "2019-08-05"
    ],
    "methods": [
      [
        "gps"
      ]
    ]
  }
}

=== wmo-im/wmdr2-devt/results/wmdr2_json_examples/20260604_0-70-0-Lukavac.json
{
  "type": "Feature",
  "id": "facility:0-70-0-Lukavac",
  "geometry": {
    "type": "Point",
    "coordinates": [
      18.5262,
      44.5213,
      188.17
    ]
  },
  "temporalGeometry": {
    "type": "MovingPoint",
    "coordinates": [
      [
        18.5262,
        44.5213,
        188.17
      ]
    ],
    "dates": [
      "2019-08-05"
    ],
    "methods": [
      [
        "gps"
      ]
    ]
  },
  "time": {
    "interval": [
      "2019-08-05",
      ".."
    ]
  },
  "conformsTo": [
    "http://wigos.wmo.int/spec/wmdr/2/conf/core"
  ],
  "properties": {
    "type": "facility",
    "title": "LUKAVAC",
    "created": "2026-06-04T00:00:00Z",
    "updated": "2026-06-04T00:00:00Z",
    "description": "WMDR2 facility record for LUKAVAC",
    "contacts": [
      {
        "organization": "Federal Hydrometeorological Institute",
        "roles": [
          "owner"
        ]
      },
      {
        "name": "Trako,Merima,Ms",
        "organization": "Federal Hydrometeorological Institute",
        "emails": [
          "merima.trako@fhmzbih.gov.ba"
        ],
        "addresses": [
          {
            "deliveryPoint": [
              "Bardakčije 12"
            ],
            "city": "Sarajevo",
            "postalCode": "71000",
            "country": "BIH"
          }
        ],
        "roles": [
          "pointOfContact"
        ]
      },
      {
        "organization": "World Meteorological Organization WMO and Federal Office for Meteorology and Climatology MeteoSwiss",
        "emails": [
          "oscar@wmo.int"
        ],
        "links": [
          {
            "href": "https://oscar.wmo.int/surface",
            "rel": "about",
            "type": "text/html"
          }
        ]
      }
    ],
    "keywords": [
      "0-70-0-Lukavac",
      "LUKAVAC"
    ],
    "links": [
      {
        "href": "https://www.fhmzbih.gov.ba/latinica/index.php",
        "rel": "about",
        "type": "text/html"
      }
    ],
    "facilityType": "underwaterFixed",
    "wmoRegion": "europe",
    "programAffiliation": [
      {
        "date": "2019-08-05",
        "programAffiliation": [
          "WHYCOS"
        ],
        "reportingStatus": "operational"
      }
    ],
    "territory": [
      {
        "date": "2019-08-05",
        "territory": "BIH"
      }
    ],
    "environment": [
      {
        "date": "2019-08-05",
        "climateZone": "snowFullyHumidWarmSummer"
      }
    ],
    "deployments": [
      {
        "id": "deployment:id_8ca504be-eb29-43a4-9ef0-a3e7a81f1ab3"
      }
    ],
    "observationSeries": [
      {
        "id": "observationSeries:166",
        "title": "domain: terrestrial; geometry: point; variable: 166",
        "observedProperty": 166,
        "observedGeometry": "point",
        "observedFeature": {
          "domain": "terrestrial"
        },
        "programAffiliation": [
          "WHYCOS"
        ],
        "observingConfigurations": [
          {
            "date": "2019-08-05",
            "deployment": "deployment:id_8ca504be-eb29-43a4-9ef0-a3e7a81f1ab3",
            "observingMethod": 356
          }
        ]
      }
    ]
  }
}

=== wmo-im/wmdr2-devt/results/wmdr2_json_examples/embedded/20250314_0-404-800-4AA01.json
{
  "type": "Feature",
  "id": "facility:0-404-800-4AA01",
  "geometry": {
    "type": "Point",
    "coordinates": [
      37.06812,
      -0.36172,
      1813
    ]
  },
  "temporalGeometry": {
    "type": "MovingPoint",
    "coordinates": [
      [
        37.06812,
        -0.36172,
        1813
      ]
    ],
    "dates": [
      "1947-09-01"
    ],
    "methods": [
      [
        "gps"
      ]
    ]
  },
  "time": {
    "interval": [
      "1947-09-01",
      ".."
    ]
  },
  "conformsTo": [
    "http://wigos.wmo.int/spec/wmdr/2/conf/core"
  ],
  "properties": {
    "type": "facility",
    "title": "['Sagana', 'Sagana in Tana Basin']",
    "created": "2025-03-14T00:00:00Z",
    "updated": "2025-03-14T00:00:00Z",
    "description": "WMDR2 facility record for ['Sagana', 'Sagana in Tana Basin']",
    "contacts": [
      {
        "organization": "Water Resources Authoriry",
        "roles": [
          "owner"
        ]
      },
      {
        "name": "MUIRURI,JOHN,Mr",
        "organization": "KENYA METEOROLOGICAL DEPARTMENT",
        "phones": [
          {
            "value": "0722442639"
          }
        ],
        "emails": [
          {
            "value": "jtmuiruri@gmail.com"
          }
        ],
        "addresses": [
          {
            "deliveryPoint": [
              "P.O BOX 30259"
            ],
            "city": "NAIROBI",
            "postalCode": "00100",
            "country": "KEN"
          }
        ],
        "roles": [
          "pointOfContact"
        ]
      },
      {
        "organization": "World Meteorological Organization WMO and Federal Office for Meteorology and Climatology MeteoSwiss",
        "emails": [
          {
            "value": "oscar@wmo.int"
          }
        ],
        "links": [
          {
            "href": "https://oscar.wmo.int/surface",
            "rel": "about",
            "type": "text/html"
          }
        ]
      }
    ],
    "keywords": [
      "0-404-800-4AA01",
      "Sagana",
      "Sagana in Tana Basin"
    ],
    "facilityType": "lakeRiverFixed",
    "wmoRegion": "africa",
    "temporalTerritory": [
      {
        "territory": "KEN",
        "date": "1947-09-01"
      }
    ],
    "temporalProgramAffiliation": [
      {
        "programAffiliation": "WHYCOS",
        "reportingStatus": "operational",
        "date": "1947-09-01"
      }
    ],
    "schedules": [
      {
        "@type": "Event",
        "start": "0001-01-01T00:00:00",
        "timeZone": "UTC",
        "duration": "P1D",
        "recurrenceRules": [
          {
            "@type": "RecurrenceRule",
            "frequency": "daily"
          }
        ],
        "wmo.int:aggregation": {
          "temporalAggregate": "PT1H"
        },
        "uid": "schedule_38ade7ec764d"
      }
    ],
    "observations": [
      {
        "id": "observation:12252",
        "title": "domain: ocean; geometry: verticalProfile; variable: 12252",
        "time": {
          "interval": [
            "1947-09-01",
            ".."
          ]
        },
        "observedVariable": 12252,
        "observedGeometryType": "verticalProfile",
        "observedDomain": "ocean",
        "programAffiliations": [
          "WHYCOS"
        ],
        "deployments": [
          "deployment:id_ca9248ad-0bba-454c-9697-8c9b98b224eb"
        ],
        "reporting": {
          "internationalExchange": [
            false
          ],
          "temporalAggregate": [
            "PT1H"
          ],
          "uom": [
            "m"
          ],
          "dataPolicy": [
            {
              "dataPolicy": "unknown",
              "attribution": {
                "originator": {
                  "role": null
                }
              }
            }
          ]
        }
      }
    ],
    "deployments": [
      {
        "id": "deployment:id_ca9248ad-0bba-454c-9697-8c9b98b224eb",
        "time": {
          "interval": [
            "1947-09-01",
            ".."
          ]
        },
        "observingMethod": 356,
        "temporalObservingSchedule": [
          {
            "observingSchedule": "schedule_38ade7ec764d",
            "date": "1947-09-01"
          }
        ]
      }
    ]
  }
}
