=== wmo-im/wmdr2-devt/schemas/wmdr2-record-feature.schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://wmo-im.github.io/wmdr2-devt/schemas/wmdr2-record-feature.schema.json",
  "title": "WMDR2 facility-centric Feature",
  "type": "object",
  "required": [
    "type",
    "id",
    "properties"
  ],
  "additionalProperties": true,
  "properties": {
    "type": {
      "const": "Feature"
    },
    "id": {
      "type": "string",
      "pattern": "^facility:"
    },
    "geometry": {
      "anyOf": [
        {
          "$ref": "wmdr2-common.schema.json#/$defs/pointGeometry"
        },
        {
          "type": "null"
        }
      ]
    },
    "temporalGeometry": {
      "$ref": "wmdr2-common.schema.json#/$defs/temporalGeometry"
    },
    "time": {
      "anyOf": [
        {
          "type": "object",
          "properties": {
            "interval": {
              "type": "array",
              "items": {
                "$ref": "wmdr2-common.schema.json#/$defs/dateOrOpen"
              },
              "minItems": 2,
              "maxItems": 2
            }
          },
          "required": [
            "interval"
          ],
          "additionalProperties": true
        },
        {
          "type": "null"
        }
      ]
    },
    "conformsTo": {
      "type": "array",
      "minItems": 1,
      "maxItems": 1,
      "items": {
        "const": "http://wigos.wmo.int/spec/wmdr/2/conf/core"
      }
    },
    "properties": {
      "type": "object",
      "required": [
        "type",
        "title"
      ],
      "additionalProperties": true,
      "allOf": [
        {
          "not": {
            "required": [
              "environment"
            ]
          }
        },
        {
          "not": {
            "required": [
              "temporalProgramAffiliation"
            ]
          }
        },
        {
          "not": {
            "required": [
              "temporalTerritory"
            ]
          }
        },
        {
          "not": {
            "required": [
              "temporalReportingStatus"
            ]
          }
        },
        {
          "not": {
            "required": [
              "externalIds"
            ]
          }
        },
        {
          "not": {
            "required": [
              "facilitySet"
            ]
          }
        },
        {
          "not": {
            "required": [
              "temporalClimateZone"
            ]
          }
        },
        {
          "not": {
            "required": [
              "temporalSurfaceCover"
            ]
          }
        },
        {
          "not": {
            "required": [
              "temporalPopulation"
            ]
          }
        },
        {
          "not": {
            "required": [
              "temporalSurfaceRoughness"
            ]
          }
        },
        {
          "not": {
            "required": [
              "temporalGeometry"
            ]
          }
        }
      ],
      "properties": {
        "type": {
          "const": "facility"
        },
        "title": {
          "type": "string"
        },
        "description": {
          "type": "string"
        },
        "created": {
          "type": "string"
        },
        "updated": {
          "type": "string"
        },
        "contacts": {
          "type": "array",
          "items": {
            "$ref": "wmdr2-common.schema.json#/$defs/contact"
          }
        },
        "keywords": {
          "type": "array",
          "items": {
            "type": "string"
          }
        },
        "links": {
          "type": "array",
          "items": {
            "$ref": "wmdr2-common.schema.json#/$defs/link"
          }
        },
        "facilitySets": {
          "type": "array",
          "items": {
            "type": "string",
            "pattern": "^facilitySet:"
          }
        },
        "historicalProgramAffiliation": {
          "$ref": "wmdr2-common.schema.json#/$defs/historicalProgramAffiliation"
        },
        "historicalTerritory": {
          "$ref": "wmdr2-common.schema.json#/$defs/historicalTerritory"
        },
        "historicalEnvironment": {
          "$ref": "wmdr2-common.schema.json#/$defs/historicalEnvironment"
        },
        "schedules": {
          "type": "array",
          "items": {
            "$ref": "wmdr2-common.schema.json#/$defs/schedule"
          }
        },
        "observations": {
          "type": "array",
          "items": {
            "$ref": "wmdr2-common.schema.json#/$defs/observation"
          }
        },
        "instruments": {
          "type": "array",
          "items": {
            "$ref": "wmdr2-common.schema.json#/$defs/instrument"
          }
        },
        "reporting": {
          "type": "array",
          "items": {
            "$ref": "wmdr2-common.schema.json#/$defs/reporting"
          }
        },
        "deployments": {
          "type": "array",
          "items": {
            "$ref": "wmdr2-common.schema.json#/$defs/deployment"
          }
        }
      }
    }
  }
}

=== wmo-im/wmdr2-devt/results/wmdr2_json_examples_catalogue_version/20250529_0-410-0-22184.json
{
  "type": "Feature",
  "id": "facility:0-410-0-22184",
  "geometry": {
    "type": "Point",
    "coordinates": [
      126.14111,
      33.79361,
      0
    ]
  },
  "time": {
    "interval": [
      "2014-01-14",
      "2024-09-30"
    ]
  },
  "conformsTo": [
    "http://wigos.wmo.int/spec/wmdr/2/conf/core"
  ],
  "properties": {
    "type": "facility",
    "title": "Chujado",
    "created": "2025-05-29T00:00:00Z",
    "updated": "2025-05-29T00:00:00Z",
    "description": "WMDR2 facility record for Chujado",
    "contacts": [
      {
        "identifier": "contact:korea-meteorology-administration--7b6d51cd",
        "organization": "Korea Meteorology Administration",
        "roles": [
          "owner"
        ],
        "links": [
          {
            "rel": "about",
            "href": "catalogues/contacts.json#contact:korea-meteorology-administration--7b6d51cd",
            "type": "application/json"
          }
        ]
      },
      {
        "identifier": "contact:oscar@wmo.int",
        "organization": "World Meteorological Organization WMO and Federal Office for Meteorology and Climatology MeteoSwiss",
        "links": [
          {
            "rel": "about",
            "href": "catalogues/contacts.json#contact:oscar@wmo.int",
            "type": "application/json"
          }
        ]
      }
    ],
    "keywords": [
      "0-410-0-22184",
      "Chujado"
    ],
    "facilityType": "seaFixed",
    "wmoRegion": "asia",
    "programAffiliation": [
      {
        "date": "2024-09-30",
        "programAffiliation": [
          "GOSGeneral"
        ],
        "reportingStatus": "closed"
      }
    ],
    "territory": [
      {
        "date": "2014-01-14",
        "territory": "KOR"
      }
    ],
    "observationSeries": [
      {
        "id": "observationSeries:95",
        "title": "domain: ocean; geometry: point; variable: 95",
        "observedProperty": 95,
        "observedGeometry": "point",
        "observedFeature": {
          "domain": "ocean"
        },
        "programAffiliation": [
          "GOSGeneral"
        ],
        "observingConfigurations": [
          {
            "observingMethod": {
              "nilReason": "unknown"
            }
          }
        ]
      },
      {
        "id": "observationSeries:98",
        "title": "domain: ocean; geometry: point; variable: 98",
        "observedProperty": 98,
        "observedGeometry": "point",
        "observedFeature": {
          "domain": "ocean"
        },
        "programAffiliation": [
          "GOSGeneral"
        ],
        "observingConfigurations": [
          {
            "observingMethod": {
              "nilReason": "unknown"
            }
          }
        ]
      },
      {
        "id": "observationSeries:99",
        "title": "domain: ocean; geometry: point; variable: 99",
        "observedProperty": 99,
        "observedGeometry": "point",
        "observedFeature": {
          "domain": "ocean"
        },
        "programAffiliation": [
          "GOSGeneral"
        ],
        "observingConfigurations": [
          {
            "observingMethod": {
              "nilReason": "unknown"
            }
          }
        ]
      },
      {
        "id": "observationSeries:100",
        "title": "domain: ocean; geometry: point; variable: 100",
        "observedProperty": 100,
        "observedGeometry": "point",
        "observedFeature": {
          "domain": "ocean"
        },
        "programAffiliation": [
          "GOSGeneral"
        ],
        "observingConfigurations": [
          {
            "observingMethod": {
              "nilReason": "unknown"
            }
          }
        ]
      },
      {
        "id": "observationSeries:216",
        "title": "domain: atmosphere; geometry: point; variable: 216",
        "observedProperty": 216,
        "observedGeometry": "point",
        "observedFeature": {
          "domain": "atmosphere"
        },
        "programAffiliation": [
          "GOSGeneral"
        ],
        "observingConfigurations": [
          {
            "observingMethod": {
              "nilReason": "unknown"
            }
          }
        ]
      },
      {
        "id": "observationSeries:224",
        "title": "domain: atmosphere; geometry: point; variable: 224",
        "observedProperty": 224,
        "observedGeometry": "point",
        "observedFeature": {
          "domain": "atmosphere"
        },
        "programAffiliation": [
          "GOSGeneral"
        ],
        "observingConfigurations": [
          {
            "observingMethod": {
              "nilReason": "unknown"
            }
          }
        ]
      },
      {
        "id": "observationSeries:12249",
        "title": "domain: atmosphere; geometry: point; variable: 12249",
        "observedProperty": 12249,
        "observedGeometry": "point",
        "observedFeature": {
          "domain": "atmosphere"
        },
        "programAffiliation": [
          "GOSGeneral"
        ],
        "observingConfigurations": [
          {
            "observingMethod": {
              "nilReason": "unknown"
            }
          }
        ]
      },
      {
        "id": "observationSeries:12005",
        "title": "domain: atmosphere; geometry: point; variable: 12005",
        "observedProperty": 12005,
        "observedGeometry": "point",
        "observedFeature": {
          "domain": "atmosphere"
        },
        "programAffiliation": [
          "GOSGeneral"
        ],
        "observingConfigurations": [
          {
            "observingMethod": {
              "nilReason": "unknown"
            }
          }
        ]
      },
      {
        "id": "observationSeries:12006",
        "title": "domain: atmosphere; geometry: point; variable: 12006",
        "observedProperty": 12006,
        "observedGeometry": "point",
        "observedFeature": {
          "domain": "atmosphere"
        },
        "programAffiliation": [
          "GOSGeneral"
        ],
        "observingConfigurations": [
          {
            "observingMethod": {
              "nilReason": "unknown"
            }
          }
        ]
      }
    ]
  }
}

=== wmo-im/wmdr2-devt/results/wmdr2_json_examples/embedded/20260604_0-70-0-Lukavac.json
{
  "type": "Feature",
  "id": "facility:0-70-0-Lukavac",
  "geometry": {
    "type": "Point",
    "coordinates": [
      18.5262,
      44.5213,
      188.17
    ]
  },
  "temporalGeometry": {
    "type": "MovingPoint",
    "coordinates": [
      [
        18.5262,
        44.5213,
        188.17
      ]
    ],
    "dates": [
      "2019-08-05"
    ],
    "methods": [
      [
        "gps"
      ]
    ]
  },
  "time": {
    "interval": [
      "2019-08-05",
      ".."
    ]
  },
  "conformsTo": [
    "http://wigos.wmo.int/spec/wmdr/2/conf/core"
  ],
  "properties": {
    "type": "facility",
    "title": "LUKAVAC",
    "created": "2026-06-04T00:00:00Z",
    "updated": "2026-06-04T00:00:00Z",
    "description": "WMDR2 facility record for LUKAVAC",
    "contacts": [
      {
        "organization": "Federal Hydrometeorological Institute",
        "roles": [
          "owner"
        ]
      },
      {
        "name": "Trako,Merima,Ms",
        "organization": "Federal Hydrometeorological Institute",
        "emails": [
          {
            "value": "merima.trako@fhmzbih.gov.ba"
          }
        ],
        "addresses": [
          {
            "deliveryPoint": [
              "Bardakčije 12"
            ],
            "city": "Sarajevo",
            "postalCode": "71000",
            "country": "BIH"
          }
        ],
        "roles": [
          "pointOfContact"
        ]
      },
      {
        "organization": "World Meteorological Organization WMO and Federal Office for Meteorology and Climatology MeteoSwiss",
        "emails": [
          {
            "value": "oscar@wmo.int"
          }
        ],
        "links": [
          {
            "href": "https://oscar.wmo.int/surface",
            "rel": "about",
            "type": "text/html"
          }
        ]
      }
    ],
    "keywords": [
      "0-70-0-Lukavac",
      "LUKAVAC"
    ],
    "links": [
      {
        "href": "https://www.fhmzbih.gov.ba/latinica/index.php",
        "rel": "about",
        "type": "text/html"
      }
    ],
    "facilityType": "underwaterFixed",
    "wmoRegion": "europe",
    "temporalTerritory": [
      {
        "territory": "BIH",
        "date": "2019-08-05"
      }
    ],
    "environment": {
      "temporalClimateZone": [
        {
          "climateZone": "snowFullyHumidWarmSummer",
          "date": "2019-08-05"
        }
      ]
    },
    "temporalProgramAffiliation": [
      {
        "programAffiliation": "WHYCOS",
        "reportingStatus": "operational",
        "date": "2019-08-05"
      }
    ],
    "observations": [
      {
        "id": "observation:166",
        "title": "domain: terrestrial; geometry: point; variable: 166",
        "time": {
          "interval": [
            "2019-08-05",
            ".."
          ]
        },
        "observedVariable": 166,
        "observedGeometryType": "point",
        "observedDomain": "terrestrial",
        "programAffiliations": [
          "WHYCOS"
        ],
        "deployments": [
          "deployment:id_8ca504be-eb29-43a4-9ef0-a3e7a81f1ab3"
        ]
      }
    ],
    "deployments": [
      {
        "id": "deployment:id_8ca504be-eb29-43a4-9ef0-a3e7a81f1ab3",
        "time": {
          "interval": [
            "2019-08-05",
            ".."
          ]
        },
        "observingMethod": 356
      }
    ]
  }
}

=== wmo-im/wmdr2-devt/results/wmdr2_json_examples_catalogue_version/20221124_0-578-0-92100.json
{
  "type": "Feature",
  "id": "facility:0-578-0-92100",
  "geometry": {
    "type": "Point",
    "coordinates": [
      2.4668,
      -71.9563,
      1235
    ]
  },
  "temporalGeometry": {
    "type": "MovingPoint",
    "coordinates": [
      [
        2.4668,
        -71.9563,
        1235
      ]
    ],
    "dates": [
      "2007-01-01"
    ],
    "methods": [
      [
        "map"
      ]
    ]
  },
  "time": {
    "interval": [
      "2007-01-01",
      ".."
    ]
  },
  "conformsTo": [
    "http://wigos.wmo.int/spec/wmdr/2/conf/core"
  ],
  "properties": {
    "type": "facility",
    "title": "TROLL AIRFIELD",
    "created": "2022-11-24T00:00:00Z",
    "updated": "2022-11-24T00:00:00Z",
    "description": "WMDR2 facility record for TROLL AIRFIELD",
    "contacts": [
      {
        "identifier": "contact:norwegian-polar-institute--8f27a0e0",
        "organization": "Norwegian Polar Institute",
        "roles": [
          "owner"
        ],
        "links": [
          {
            "rel": "about",
            "href": "catalogues/contacts.json#contact:norwegian-polar-institute--8f27a0e0",
            "type": "application/json"
          }
        ]
      },
      {
        "identifier": "contact:christina.pedersen@npolar.no",
        "name": "Pedersen,Christina Alsvik,Dr.",
        "organization": "Norwegian Polar Institute",
        "roles": [
          "principalInvestigator"
        ],
        "links": [
          {
            "rel": "about",
            "href": "catalogues/contacts.json#contact:christina.pedersen@npolar.no",
            "type": "application/json"
          }
        ]
      },
      {
        "identifier": "contact:oscar@wmo.int",
        "organization": "World Meteorological Organization WMO and Federal Office for Meteorology and Climatology MeteoSwiss",
        "links": [
          {
            "rel": "about",
            "href": "catalogues/contacts.json#contact:oscar@wmo.int",
            "type": "application/json"
          }
        ]
      }
    ],
    "keywords": [
      "0-578-0-92100",
      "TROLL AIRFIELD"
    ],
    "facilityType": "landOnIce",
    "wmoRegion": "antarctica",
    "programAffiliation": [
      {
        "date": "2022-11-22",
        "programAffiliation": [
          "GOSGeneral"
        ],
        "reportingStatus": "operational"
      },
      {
        "date": "2022-11-22",
        "programAffiliation": [
          "nonAffiliated"
        ],
        "reportingStatus": "operational"
      }
    ],
    "territory": [
      {
        "date": "2007-01-01",
        "territory": "NOR"
      }
    ],
    "deployments": [
      {
        "id": "deployment:id_98af3b44-3633-4017-b16a-8dfb89707c55"
      },
      {
        "id": "deployment:id_1c5901b1-da2a-46dd-9d48-6afb6a876cb4"
      },
      {
        "id": "deployment:id_86c6bc2c-7e41-4c5e-b8db-7f6147d34c68"
      },
      {
        "id": "deployment:id_1219f00c-7af8-432b-be2a-9a442a76e14a"
      }
    ],
    "observationSeries": [
      {
        "id": "observationSeries:216",
        "title": "domain: atmosphere; geometry: point; variable: 216",
        "observedProperty": 216,
        "observedGeometry": "point",
        "observedFeature": {
          "domain": "atmosphere"
        },
        "programAffiliation": [
          "nonAffiliated",
          "GOSGeneral"
        ],
        "observingConfigurations": [
          {
            "date": "2007-01-01",
            "deployment": "deployment:id_98af3b44-3633-4017-b16a-8dfb89707c55",
            "observingMethod": 111
          }
        ]
      },
      {
        "id": "observationSeries:224",
        "title": "domain: atmosphere; geometry: point; variable: 224",
        "observedProperty": 224,
        "observedGeometry": "point",
        "observedFeature": {
          "domain": "atmosphere"
        },
        "programAffiliation": [
          "nonAffiliated",
          "GOSGeneral"
        ],
        "observingConfigurations": [
          {
            "date": "2007-01-01",
            "deployment": "deployment:id_1c5901b1-da2a-46dd-9d48-6afb6a876cb4",
            "observingMethod": 188
          }
        ]
      },
      {
        "id": "observationSeries:12249",
        "title": "domain: atmosphere; geometry: point; variable: 12249",
        "observedProperty": 12249,
        "observedGeometry": "point",
        "observedFeature": {
          "domain": "atmosphere"
        },
        "programAffiliation": [
          "nonAffiliated",
          "GOSGeneral"
        ],
        "observingConfigurations": [
          {
            "date": "2022-11-22",
            "deployment": "deployment:id_86c6bc2c-7e41-4c5e-b8db-7f6147d34c68",
            "observingMethod": 254
          }
        ]
      },
      {
        "id": "observationSeries:12005",
        "title": "domain: atmosphere; geometry: point; variable: 12005",
        "observedProperty": 12005,
        "observedGeometry": "point",
        "observedFeature": {
          "domain": "atmosphere"
        },
        "programAffiliation": [
          "nonAffiliated",
          "GOSGeneral"
        ],
        "observingConfigurations": [
          {
            "date": "2007-01-01",
            "deployment": "deployment:id_1219f00c-7af8-432b-be2a-9a442a76e14a",
            "observingMethod": 63
          }
        ]
      }
    ]
  }
}

=== wmo-im/wmdr2-devt/results/wmdr2_json_examples/catalogue_records/20230331_0-250-1005-SARg.json
{
  "type": "Feature",
  "id": "facility:0-250-1005-SARg",
  "geometry": {
    "type": "Point",
    "coordinates": [
      6.07,
      45.07,
      2850
    ]
  },
  "time": {
    "interval": [
      "1949-01-01",
      ".."
    ]
  },
  "conformsTo": [
    "http://wigos.wmo.int/spec/wmdr/2/conf/core"
  ],
  "properties": {
    "type": "facility",
    "title": "Sarennes Glacier",
    "created": "2023-03-31T00:00:00Z",
    "updated": "2023-03-31T00:00:00Z",
    "description": "WMDR2 facility record for Sarennes Glacier",
    "contacts": [
      {
        "identifier": "contact:universit-grenoble-alpes--85858f8c",
        "organization": "Université Grenoble-Alpes",
        "roles": [
          "owner"
        ],
        "links": [
          {
            "rel": "about",
            "href": "../contacts.json#contact:universit-grenoble-alpes--85858f8c",
            "type": "application/json"
          }
        ]
      },
      {
        "identifier": "contact:delphine.six@univ-grenoble-alpes.fr",
        "name": "SIX,Delphine,Mme",
        "organization": "Université Grenoble-Alpes",
        "roles": [
          "principalInvestigator"
        ],
        "links": [
          {
            "rel": "about",
            "href": "../contacts.json#contact:delphine.six@univ-grenoble-alpes.fr",
            "type": "application/json"
          }
        ]
      },
      {
        "identifier": "contact:oscar@wmo.int",
        "organization": "World Meteorological Organization WMO and Federal Office for Meteorology and Climatology MeteoSwiss",
        "links": [
          {
            "rel": "about",
            "href": "../contacts.json#contact:oscar@wmo.int",
            "type": "application/json"
          }
        ]
      }
    ],
    "keywords": [
      "0-250-1005-SARg",
      "Sarennes Glacier"
    ],
    "links": [
      {
        "href": "https://glacioclim.osug.fr/Glacier-de-Sarennes-203",
        "rel": "about",
        "type": "text/html"
      }
    ],
    "facilityType": "landOnIce",
    "wmoRegion": "europe",
    "temporalTerritory": [
      {
        "territory": "FRA",
        "date": "1949-01-01"
      }
    ],
    "schedules": [
      {
        "@type": "Event",
        "start": "0001-01-01T00:00:00",
        "timeZone": "UTC",
        "duration": "P1D",
        "recurrenceRules": [
          {
            "@type": "RecurrenceRule",
            "frequency": "daily"
          }
        ],
        "wmo.int:aggregation": {
          "temporalAggregate": "PT1H"
        },
        "uid": "schedule_38ade7ec764d"
      }
    ],
    "observations": [
      {
        "id": "observation:12010",
        "title": "domain: terrestrial; geometry: unknown; variable: 12010",
        "time": {
          "interval": [
            "1949-01-01",
            ".."
          ]
        },
        "observedVariable": 12010,
        "observedGeometryType": "unknown",
        "observedDomain": "terrestrial",
        "programAffiliations": [
          "nonAffiliated"
        ],
        "deployments": [
          "deployment:id_14ca4229-9da7-4f5c-8e35-5a30369f353c"
        ],
        "reporting": {
          "internationalExchange": [
            false
          ],
          "temporalAggregate": [
            "PT1H"
          ]
        }
      }
    ],
    "deployments": [
      {
        "id": "deployment:id_14ca4229-9da7-4f5c-8e35-5a30369f353c",
        "time": {
          "interval": [
            "1949-01-01",
            ".."
          ]
        },
        "observingMethod": "unknown",
        "temporalObservingSchedule": [
          {
            "observingSchedule": "schedule_38ade7ec764d",
            "date": "1949-01-01"
          }
        ]
      }
    ]
  }
}

=== wmo-im/wmdr2-devt/results/wmdr2_json_examples/catalogue_based/20230331_0-250-1005-SARg.json
{
  "type": "Feature",
  "id": "facility:0-250-1005-SARg",
  "geometry": {
    "type": "Point",
    "coordinates": [
      6.07,
      45.07,
      2850
    ]
  },
  "time": {
    "interval": [
      "1949-01-01",
      ".."
    ]
  },
  "conformsTo": [
    "http://wigos.wmo.int/spec/wmdr/2/conf/core"
  ],
  "properties": {
    "type": "facility",
    "title": "Sarennes Glacier",
    "created": "2023-03-31T00:00:00Z",
    "updated": "2023-03-31T00:00:00Z",
    "description": "WMDR2 facility record for Sarennes Glacier",
    "contacts": [
      {
        "identifier": "contact:universit-grenoble-alpes--85858f8c",
        "organization": "Université Grenoble-Alpes",
        "roles": [
          "owner"
        ],
        "links": [
          {
            "rel": "about",
            "href": "catalogues/contacts.json#contact:universit-grenoble-alpes--85858f8c",
            "type": "application/json"
          }
        ]
      },
      {
        "identifier": "contact:delphine.six@univ-grenoble-alpes.fr",
        "name": "SIX,Delphine,Mme",
        "organization": "Université Grenoble-Alpes",
        "roles": [
          "principalInvestigator"
        ],
        "links": [
          {
            "rel": "about",
            "href": "catalogues/contacts.json#contact:delphine.six@univ-grenoble-alpes.fr",
            "type": "application/json"
          }
        ]
      },
      {
        "identifier": "contact:oscar@wmo.int",
        "organization": "World Meteorological Organization WMO and Federal Office for Meteorology and Climatology MeteoSwiss",
        "links": [
          {
            "rel": "about",
            "href": "catalogues/contacts.json#contact:oscar@wmo.int",
            "type": "application/json"
          }
        ]
      }
    ],
    "keywords": [
      "0-250-1005-SARg",
      "Sarennes Glacier"
    ],
    "links": [
      {
        "href": "https://glacioclim.osug.fr/Glacier-de-Sarennes-203",
        "rel": "about",
        "type": "text/html"
      }
    ],
    "facilityType": "landOnIce",
    "wmoRegion": "europe",
    "programAffiliation": [
      {
        "date": "1949-01-01",
        "programAffiliation": [
          "nonAffiliated"
        ]
      }
    ],
    "territory": [
      {
        "date": "1949-01-01",
        "territory": "FRA"
      }
    ],
    "schedules": [
      {
        "@type": "Event",
        "start": "0001-01-01T00:00:00",
        "timeZone": "UTC",
        "duration": "PT1H",
        "recurrenceRules": [
          {
            "@type": "RecurrenceRule",
            "frequency": "hourly"
          }
        ],
        "wmo.int:aggregationInterval": "PT1H",
        "uid": "schedule_f253213a5423"
      }
    ],
    "reporting": [
      {
        "id": "reporting:87ff24b4a55a",
        "internationalExchange": false,
        "temporalAggregate": "PT1H"
      }
    ],
    "deployments": [
      {
        "id": "deployment:id_14ca4229-9da7-4f5c-8e35-5a30369f353c",
        "date": "1949-01-01"
      }
    ],
    "observationSeries": [
      {
        "id": "observationSeries:12010",
        "title": "domain: terrestrial; geometry: unknown; variable: 12010",
        "time": {
          "interval": [
            "1949-01-01",
            ".."
          ]
        },
        "observedProperty": 12010,
        "observedGeometry": "unknown",
        "observedFeature": {
          "domain": "terrestrial"
        },
        "programAffiliation": [
          "nonAffiliated"
        ],
        "observingProcedures": [
          {
            "date": "1949-01-01",
            "strategy": "unknown",
            "observingSchedules": [
              "schedule_f253213a5423"
            ]
          }
        ],
        "deployments": [
          "deployment:id_14ca4229-9da7-4f5c-8e35-5a30369f353c"
        ],
        "reporting": [
          {
            "date": "1949-01-01",
            "strategy": "unknown",
            "reporting": "reporting:87ff24b4a55a"
          }
        ]
      }
    ]
  }
}
