=== wmo-im/wmdr2-devt/schemas/wmdr2-record-feature.schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://wmo-im.github.io/wmdr2-devt/schemas/wmdr2-record-feature.schema.json",
  "title": "WMDR2 facility-centric Feature",
  "type": "object",
  "required": [
    "type",
    "id",
    "properties"
  ],
  "additionalProperties": true,
  "properties": {
    "type": {
      "const": "Feature"
    },
    "id": {
      "type": "string",
      "pattern": "^facility:"
    },
    "geometry": {
      "anyOf": [
        {
          "$ref": "wmdr2-common.schema.json#/$defs/pointGeometry"
        },
        {
          "type": "null"
        }
      ]
    },
    "temporalGeometry": {
      "$ref": "wmdr2-common.schema.json#/$defs/temporalGeometry"
    },
    "time": {
      "anyOf": [
        {
          "type": "object",
          "properties": {
            "interval": {
              "type": "array",
              "items": {
                "$ref": "wmdr2-common.schema.json#/$defs/dateOrOpen"
              },
              "minItems": 2,
              "maxItems": 2
            }
          },
          "required": [
            "interval"
          ],
          "additionalProperties": true
        },
        {
          "type": "null"
        }
      ]
    },
    "conformsTo": {
      "type": "array",
      "minItems": 1,
      "maxItems": 1,
      "items": {
        "const": "http://wigos.wmo.int/spec/wmdr/2/conf/core"
      }
    },
    "properties": {
      "type": "object",
      "required": [
        "type",
        "title"
      ],
      "additionalProperties": true,
      "allOf": [
        {
          "not": {
            "required": [
              "environment"
            ]
          }
        },
        {
          "not": {
            "required": [
              "temporalProgramAffiliation"
            ]
          }
        },
        {
          "not": {
            "required": [
              "temporalTerritory"
            ]
          }
        },
        {
          "not": {
            "required": [
              "temporalReportingStatus"
            ]
          }
        },
        {
          "not": {
            "required": [
              "externalIds"
            ]
          }
        },
        {
          "not": {
            "required": [
              "facilitySet"
            ]
          }
        },
        {
          "not": {
            "required": [
              "temporalClimateZone"
            ]
          }
        },
        {
          "not": {
            "required": [
              "temporalSurfaceCover"
            ]
          }
        },
        {
          "not": {
            "required": [
              "temporalPopulation"
            ]
          }
        },
        {
          "not": {
            "required": [
              "temporalSurfaceRoughness"
            ]
          }
        },
        {
          "not": {
            "required": [
              "temporalGeometry"
            ]
          }
        }
      ],
      "properties": {
        "type": {
          "const": "facility"
        },
        "title": {
          "type": "string"
        },
        "description": {
          "type": "string"
        },
        "created": {
          "type": "string"
        },
        "updated": {
          "type": "string"
        },
        "contacts": {
          "type": "array",
          "items": {
            "$ref": "wmdr2-common.schema.json#/$defs/contact"
          }
        },
        "keywords": {
          "type": "array",
          "items": {
            "type": "string"
          }
        },
        "links": {
          "type": "array",
          "items": {
            "$ref": "wmdr2-common.schema.json#/$defs/link"
          }
        },
        "facilitySets": {
          "type": "array",
          "items": {
            "type": "string",
            "pattern": "^facilitySet:"
          }
        },
        "historicalProgramAffiliation": {
          "$ref": "wmdr2-common.schema.json#/$defs/historicalProgramAffiliation"
        },
        "historicalTerritory": {
          "$ref": "wmdr2-common.schema.json#/$defs/historicalTerritory"
        },
        "historicalEnvironment": {
          "$ref": "wmdr2-common.schema.json#/$defs/historicalEnvironment"
        },
        "schedules": {
          "type": "array",
          "items": {
            "$ref": "wmdr2-common.schema.json#/$defs/schedule"
          }
        },
        "observations": {
          "type": "array",
          "items": {
            "$ref": "wmdr2-common.schema.json#/$defs/observation"
          }
        },
        "instruments": {
          "type": "array",
          "items": {
            "$ref": "wmdr2-common.schema.json#/$defs/instrument"
          }
        },
        "reporting": {
          "type": "array",
          "items": {
            "$ref": "wmdr2-common.schema.json#/$defs/reporting"
          }
        },
        "deployments": {
          "type": "array",
          "items": {
            "$ref": "wmdr2-common.schema.json#/$defs/deployment"
          }
        }
      }
    }
  }
}

=== wmo-im/wmdr2-devt/results/wmdr2_json_examples_catalogue_version/20240806_0-840-11502-KominkoSlade.json
{
  "type": "Feature",
  "id": "0-840-11502-KominkoSlade",
  "conformsTo": [
    "http://wigos.wmo.int/spec/wmdr/2/conf/core"
  ],
  "geometry": {
    "type": "Point",
    "coordinates": [
      -112.106,
      -79.466,
      1801
    ]
  },
  "properties": {
    "type": "facility",
    "title": "Kominko-Slade (WAIS)",
    "created": "2024-08-06T00:00:00Z",
    "updated": "2024-08-06T00:00:00Z",
    "facilityType": "landOnIce",
    "territory": [
      {
        "territory": "USA",
        "time": {
          "interval": [
            "2006-01-13",
            ".."
          ]
        }
      }
    ],
    "wmoRegion": "antarctica",
    "observationSeries": [
      {
        "id": "observationSeries:216",
        "title": "domain: atmosphere; variable: 216",
        "observedProperty": 216,
        "observedDomain": {
          "domain": "atmosphere"
        },
        "observingConfigurations": [
          {
            "time": {
              "interval": [
                "2006-01-13",
                ".."
              ]
            },
            "observingMethod": 111,
            "sourceOfObservation": "automaticReading",
            "exposure": "class1",
            "verticalDistanceFromReferenceSurface": {
              "value": 2.0,
              "uom": "m"
            },
            "geometry": {
              "type": "Point",
              "coordinates": [
                -112.106,
                -79.466,
                1801
              ]
            },
            "instrument": "instrument:paroscientific-series-2000-absolute-and-gauge-pressure-transducers-215a-102"
          }
        ],
        "observingProcedures": [
          {
            "observingSchedules": [
              "schedule_ec0955d7b9"
            ],
            "time": {
              "interval": [
                "2006-01-13",
                ".."
              ]
            }
          }
        ],
        "reportingProcedures": [
          {
            "internationalExchange": false,
            "uom": "hPa",
            "reportingSchedules": [
              "schedule_ec0955d7b9"
            ]
          }
        ]
      },
      {
        "id": "observationSeries:224",
        "title": "domain: atmosphere; variable: 224",
        "observedProperty": 224,
        "observedDomain": {
          "domain": "atmosphere"
        },
        "observingConfigurations": [
          {
            "time": {
              "interval": [
                "2006-01-13",
                ".."
              ]
            },
            "observingMethod": 188,
            "sourceOfObservation": "humanObservation",
            "exposure": "class2",
            "verticalDistanceFromReferenceSurface": {
              "value": 2.0,
              "uom": "m"
            },
            "geometry": {
              "type": "Point",
              "coordinates": [
                -112.106,
                -79.466,
                1801
              ]
            },
            "instrument": "instrument:weed-instrument-platinum-resistance-thermometer-prt"
          }
        ],
        "observingProcedures": [
          {
            "observingSchedules": [
              "schedule_ec0955d7b9"
            ],
            "time": {
              "interval": [
                "2006-01-13",
                ".."
              ]
            }
          }
        ],
        "reportingProcedures": [
          {
            "internationalExchange": false,
            "uom": "degC",
            "reportingSchedules": [
              "schedule_ec0955d7b9"
            ]
          }
        ]
      },
      {
        "id": "observationSeries:12249",
        "title": "domain: atmosphere; variable: 12249",
        "observedProperty": 12249,
        "observedDomain": {
          "domain": "atmosphere"
        },
        "observingConfigurations": [
          {
            "time": {
              "interval": [
                "2006-01-13",
                ".."
              ]
            },
            "observingMethod": 250,
            "sourceOfObservation": "automaticReading",
            "exposure": "class2",
            "verticalDistanceFromReferenceSurface": {
              "value": 2.0,
              "uom": "m"
            },
            "geometry": {
              "type": "Point",
              "coordinates": [
                -112.106,
                -79.466,
                1801
              ]
            },
            "instrument": "instrument:vaisala-oyj-vaisala-hmp45a"
          }
        ],
        "observingProcedures": [
          {
            "observingSchedules": [
              "schedule_ec0955d7b9"
            ],
            "time": {
              "interval": [
                "2006-01-13",
                ".."
              ]
            }
          }
        ],
        "reportingProcedures": [
          {
            "internationalExchange": false,
            "uom": "percent",
            "reportingSchedules": [
              "schedule_ec0955d7b9"
            ]
          }
        ]
      },
      {
        "id": "observationSeries:12005",
        "title": "domain: atmosphere; variable: 12005",
        "observedProperty": 12005,
        "observedDomain": {
          "domain": "atmosphere"
        },
        "observingConfigurations": [
          {
            "time": {
              "interval": [
                "2006-01-13",
                ".."
              ]
            },
            "observingMethod": 65,
            "sourceOfObservation": "automaticReading",
            "exposure": "class2",
            "verticalDistanceFromReferenceSurface": {
              "value": 3.0,
              "uom": "m"
            },
            "geometry": {
              "type": "Point",
              "coordinates": [
                -112.106,
                -79.466,
                1801
              ]
            },
            "instrument": "instrument:rm-young-wind-monitor-hd-alpine-05108-45"
          }
        ],
        "observingProcedures": [
          {
            "observingSchedules": [
              "schedule_ec0955d7b9"
            ],
            "time": {
              "interval": [
                "2006-01-13",
                ".."
              ]
            }
          }
        ],
        "reportingProcedures": [
          {
            "internationalExchange": false,
            "uom": "deg",
            "reportingSchedules": [
              "schedule_ec0955d7b9"
            ]
          }
        ]
      },
      {
        "id": "observationSeries:12006",
        "title": "domain: atmosphere; variable: 12006",
        "observedProperty": 12006,
        "observedDomain": {
          "domain": "atmosphere"
        },
        "observingConfigurations": [
          {
            "time": {
              "interval": [
                "2006-01-13",
                ".."
              ]
            },
            "observingMethod": 65,
            "sourceOfObservation": "automaticReading",
            "exposure": "class2",
            "verticalDistanceFromReferenceSurface": {
              "value": 3.0,
              "uom": "m"
            },
            "geometry": {
              "type": "Point",
              "coordinates": [
                -112.106,
                -79.466,
                1801
              ]
            },
            "instrument": "instrument:rm-young-wind-monitor-hd-alpine-05108-45"
          }
        ],
        "observingProcedures": [
          {
            "observingSchedules": [
              "schedule_ec0955d7b9"
            ],
            "time": {
              "interval": [
                "2006-01-13",
                ".."
              ]
            }
          }
        ],
        "reportingProcedures": [
          {
            "internationalExchange": false,
            "uom": "m.s-1",
            "reportingSchedules": [
              "schedule_ec0955d7b9"
            ]
          }
        ]
      }
    ],
    "schedules": [
      {
        "wmo.int:aggregationInterval": "PT3H",
        "start": "0001-01-01T00:00:00",
        "duration": "PT23H59M",
        "@type": "Event",
        "uid": "schedule_ec0955d7b9"
      }
    ],
    "keywords": [
      "0-840-11502-KominkoSlade",
      "Kominko-Slade (WAIS)"
    ],
    "links": [
      {
        "href": "https://amrc.ssec.wisc.edu/aws/index.php?region=West%20Antarctica&station=Kominko-Slade%20(WAIS)&year=2022",
        "rel": "about",
        "type": "text/html"
      },
      {
        "href": "https://amrdcdata.ssec.wisc.edu/",
        "rel": "about",
        "type": "text/html"
      }
    ],
    "contactAssignments": [
      {
        "contact": "contact:mattl@ssec.wisc.edu",
        "roles": [
          "pointOfContact"
        ]
      }
    ]
  },
  "time": {
    "interval": [
      "2006-01-13",
      ".."
    ],
    "resolution": "P1D"
  },
  "temporalGeometry": {
    "type": "MovingPoint",
    "coordinates": [
      [
        -112.086,
        -79.468,
        1833
      ],
      [
        -112.106,
        -79.466,
        1801
      ],
      [
        -112.106,
        -79.465,
        1803
      ],
      [
        -112.106,
        -79.466,
        1801
      ]
    ],
    "dates": [
      "2006-01-13",
      "2009-01-26",
      "2010-01-20",
      "2011-12-17"
    ],
    "methods": [
      [
        "gps"
      ],
      [
        "gps"
      ],
      [
        "gps"
      ],
      [
        "gps"
      ]
    ]
  }
}

=== wmo-im/wmdr2-devt/results/wmdr2_json_examples/catalogue_records/20250529_0-410-0-22184.json
{
  "type": "Feature",
  "id": "facility:0-410-0-22184",
  "geometry": {
    "type": "Point",
    "coordinates": [
      126.14111,
      33.79361,
      0
    ]
  },
  "time": {
    "interval": [
      "2014-01-14",
      "2024-09-30"
    ]
  },
  "conformsTo": [
    "http://wigos.wmo.int/spec/wmdr/2/conf/core"
  ],
  "properties": {
    "type": "facility",
    "title": "Chujado",
    "created": "2025-05-29T00:00:00Z",
    "updated": "2025-05-29T00:00:00Z",
    "description": "WMDR2 facility record for Chujado",
    "contacts": [
      {
        "identifier": "contact:korea-meteorology-administration--7b6d51cd",
        "organization": "Korea Meteorology Administration",
        "roles": [
          "owner"
        ],
        "links": [
          {
            "rel": "about",
            "href": "../contacts.json#contact:korea-meteorology-administration--7b6d51cd",
            "type": "application/json"
          }
        ]
      },
      {
        "identifier": "contact:oscar@wmo.int",
        "organization": "World Meteorological Organization WMO and Federal Office for Meteorology and Climatology MeteoSwiss",
        "links": [
          {
            "rel": "about",
            "href": "../contacts.json#contact:oscar@wmo.int",
            "type": "application/json"
          }
        ]
      }
    ],
    "keywords": [
      "0-410-0-22184",
      "Chujado"
    ],
    "facilityType": "seaFixed",
    "wmoRegion": "asia",
    "temporalTerritory": [
      {
        "territory": "KOR",
        "date": "2014-01-14"
      }
    ],
    "temporalProgramAffiliation": [
      {
        "programAffiliation": "GOSGeneral",
        "reportingStatus": "closed",
        "date": "2024-09-30"
      }
    ],
    "observations": [
      {
        "id": "observation:95",
        "title": "domain: ocean; geometry: point; variable: 95",
        "observedVariable": 95,
        "observedGeometryType": "point",
        "observedDomain": "ocean",
        "programAffiliations": [
          "GOSGeneral"
        ]
      },
      {
        "id": "observation:98",
        "title": "domain: ocean; geometry: point; variable: 98",
        "observedVariable": 98,
        "observedGeometryType": "point",
        "observedDomain": "ocean",
        "programAffiliations": [
          "GOSGeneral"
        ]
      },
      {
        "id": "observation:99",
        "title": "domain: ocean; geometry: point; variable: 99",
        "observedVariable": 99,
        "observedGeometryType": "point",
        "observedDomain": "ocean",
        "programAffiliations": [
          "GOSGeneral"
        ]
      },
      {
        "id": "observation:100",
        "title": "domain: ocean; geometry: point; variable: 100",
        "observedVariable": 100,
        "observedGeometryType": "point",
        "observedDomain": "ocean",
        "programAffiliations": [
          "GOSGeneral"
        ]
      },
      {
        "id": "observation:216",
        "title": "domain: atmosphere; geometry: point; variable: 216",
        "observedVariable": 216,
        "observedGeometryType": "point",
        "observedDomain": "atmosphere",
        "programAffiliations": [
          "GOSGeneral"
        ]
      },
      {
        "id": "observation:224",
        "title": "domain: atmosphere; geometry: point; variable: 224",
        "observedVariable": 224,
        "observedGeometryType": "point",
        "observedDomain": "atmosphere",
        "programAffiliations": [
          "GOSGeneral"
        ]
      },
      {
        "id": "observation:12249",
        "title": "domain: atmosphere; geometry: point; variable: 12249",
        "observedVariable": 12249,
        "observedGeometryType": "point",
        "observedDomain": "atmosphere",
        "programAffiliations": [
          "GOSGeneral"
        ]
      },
      {
        "id": "observation:12005",
        "title": "domain: atmosphere; geometry: point; variable: 12005",
        "observedVariable": 12005,
        "observedGeometryType": "point",
        "observedDomain": "atmosphere",
        "programAffiliations": [
          "GOSGeneral"
        ]
      },
      {
        "id": "observation:12006",
        "title": "domain: atmosphere; geometry: point; variable: 12006",
        "observedVariable": 12006,
        "observedGeometryType": "point",
        "observedDomain": "atmosphere",
        "programAffiliations": [
          "GOSGeneral"
        ]
      }
    ]
  }
}

=== wmo-im/wmdr2-devt/results/wmdr2_json_examples/20250529_0-410-0-22184.json
{
  "type": "Feature",
  "id": "facility:0-410-0-22184",
  "geometry": {
    "type": "Point",
    "coordinates": [
      126.14111,
      33.79361,
      0
    ]
  },
  "time": {
    "interval": [
      "2014-01-14",
      "2024-09-30"
    ]
  },
  "conformsTo": [
    "http://wigos.wmo.int/spec/wmdr/2/conf/core"
  ],
  "properties": {
    "type": "facility",
    "title": "Chujado",
    "created": "2025-05-29T00:00:00Z",
    "updated": "2025-05-29T00:00:00Z",
    "description": "WMDR2 facility record for Chujado",
    "contacts": [
      {
        "organization": "Korea Meteorology Administration",
        "roles": [
          "owner"
        ]
      },
      {
        "organization": "World Meteorological Organization WMO and Federal Office for Meteorology and Climatology MeteoSwiss",
        "emails": [
          {
            "value": "oscar@wmo.int"
          }
        ],
        "links": [
          {
            "href": "https://oscar.wmo.int/surface",
            "rel": "about",
            "type": "text/html"
          }
        ]
      }
    ],
    "keywords": [
      "0-410-0-22184",
      "Chujado"
    ],
    "facilityType": "seaFixed",
    "wmoRegion": "asia",
    "temporalTerritory": [
      {
        "territory": "KOR",
        "date": "2014-01-14"
      }
    ],
    "temporalProgramAffiliation": [
      {
        "programAffiliation": "GOSGeneral",
        "reportingStatus": "closed",
        "date": "2024-09-30"
      }
    ],
    "observations": [
      {
        "id": "observation:95",
        "title": "domain: ocean; geometry: point; variable: 95",
        "observedProperty": 95,
        "observedGeometry": "point",
        "observedDomain": {
          "domain": "ocean"
        },
        "programAffiliations": [
          "GOSGeneral"
        ]
      },
      {
        "id": "observation:98",
        "title": "domain: ocean; geometry: point; variable: 98",
        "observedProperty": 98,
        "observedGeometry": "point",
        "observedDomain": {
          "domain": "ocean"
        },
        "programAffiliations": [
          "GOSGeneral"
        ]
      },
      {
        "id": "observation:99",
        "title": "domain: ocean; geometry: point; variable: 99",
        "observedProperty": 99,
        "observedGeometry": "point",
        "observedDomain": {
          "domain": "ocean"
        },
        "programAffiliations": [
          "GOSGeneral"
        ]
      },
      {
        "id": "observation:100",
        "title": "domain: ocean; geometry: point; variable: 100",
        "observedProperty": 100,
        "observedGeometry": "point",
        "observedDomain": {
          "domain": "ocean"
        },
        "programAffiliations": [
          "GOSGeneral"
        ]
      },
      {
        "id": "observation:216",
        "title": "domain: atmosphere; geometry: point; variable: 216",
        "observedProperty": 216,
        "observedGeometry": "point",
        "observedDomain": {
          "domain": "atmosphere"
        },
        "programAffiliations": [
          "GOSGeneral"
        ]
      },
      {
        "id": "observation:224",
        "title": "domain: atmosphere; geometry: point; variable: 224",
        "observedProperty": 224,
        "observedGeometry": "point",
        "observedDomain": {
          "domain": "atmosphere"
        },
        "programAffiliations": [
          "GOSGeneral"
        ]
      },
      {
        "id": "observation:12249",
        "title": "domain: atmosphere; geometry: point; variable: 12249",
        "observedProperty": 12249,
        "observedGeometry": "point",
        "observedDomain": {
          "domain": "atmosphere"
        },
        "programAffiliations": [
          "GOSGeneral"
        ]
      },
      {
        "id": "observation:12005",
        "title": "domain: atmosphere; geometry: point; variable: 12005",
        "observedProperty": 12005,
        "observedGeometry": "point",
        "observedDomain": {
          "domain": "atmosphere"
        },
        "programAffiliations": [
          "GOSGeneral"
        ]
      },
      {
        "id": "observation:12006",
        "title": "domain: atmosphere; geometry: point; variable: 12006",
        "observedProperty": 12006,
        "observedGeometry": "point",
        "observedDomain": {
          "domain": "atmosphere"
        },
        "programAffiliations": [
          "GOSGeneral"
        ]
      }
    ]
  }
}
